# kubectl create deployment result-deployment --image=kodekloud/examplevotingapp_result:before --dry-run -oyaml -n vote > result-deployment.yaml
# Edit the container name, it won't take underscore in container name. 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-deployment
  name: result-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-deployment
  template:
    metadata:
      labels:
        app: result-deployment
    spec:
      containers:
      - image: kodekloud/examplevotingapp_result:before
        name: examplevotingapp-result

